on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk:latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: |
          make -f Makefile
      - uses: actions/upload-artifact@v4
        with:
          name: NETW
          path: ./NETW
