on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk:latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: build
        id: build
        run: |
          make -f Makefile
      - uses: actions/upload-artifact@v4
        with:
          name: NEWT
          path: ./NEWT
